Feature init
R2D2-2018/MOVING_PLATFORM pull request #11
Opened 2018-06-04 10:14 UTC by olivierverwoerd

2018-06-08 11:53 UTC, JasperSmienk commented on src/moving_platform.hpp
> +/**
All the @param[in] commands in this file need a parameter name.

2018-06-08 11:54 UTC, JasperSmienk commented on src/moving_platform.hpp
> +    /// This is designed to break. waiting for motorcontroller to
Useless comment.

2018-06-08 12:06 UTC, JasperSmienk commented on src/moving_platform.hpp
> + * @brief Platform
Doxygen knows which class/function this comment paragraph corresponds to and shows that name as the title, so simply copying the name is useless.
Change this and all other @brief's in this file that have just the name to a more descriptive sentence.

2018-06-08 12:07 UTC, ghost requested changes
Looks good besides some small doxygen errors.

2018-06-13 17:23 UTC, Danielvv1998 commented
I fixed the doxygen and updated the methods to fit the interface mentioned in the vertical slice. @JasperSmienk

2018-06-14 10:43 UTC, JasperSmienk commented
@Danielvv1998 The @param[in] commands still need the name of the parameter.
e.g. @param[in] <parameter> <description>

2018-06-14 11:24 UTC, ghost approved these changes

2018-06-14 11:25 UTC, ghost commented
Everything is updated and fixed now, merging pull-request.

2018-06-14 11:25 UTC, merged